### ISSUE TITLE
draw.eset.QC function pre_define color only work for box plot

### ISSUE THREAD

**Issue by jingl87** [jyyulab/NetBID#4]
<img width="634" alt="Screen Shot 2020-07-27 at 12 58 25 PM" src="https://user-images.githubusercontent.com/19508721/88575061-e8118700-d008-11ea-9d78-234297bd61ed.png">
<img width="634" alt="Screen Shot 2020-07-27 at 12 58 37 PM" src="https://user-images.githubusercontent.com/19508721/88575066-ea73e100-d008-11ea-831c-ba2b7281a544.png">

**Comment by SherryDong** [comment]
Thanks, I will modify the script !

**Comment by UjvLtL9FYquRPKnbkyrEtvnVuUgIt5lGnb4REw7** [comment]
Thanks, I will modify the script !
